apiVersion: v1
kind: Namespace
metadata:
  name: build-tomo-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-build-jobs-manager
  namespace: build-tomo-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-tomo-dev
  namespace: build-tomo-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-manage-build-jobs
  namespace: build-tomo-dev
subjects:
- kind: ServiceAccount
  name: build-tomo-dev
  apiGroup: ""
roleRef:
  kind: Role
  name: dev-build-jobs-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: tomo-job
  name: tomo-job
  namespace: build-tomo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomo-job
  template:
    metadata:
      labels:
        app: tomo-job
    spec:
      serviceAccount: build-tomo-dev
      securityContext:
        runAsUser: 0
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: p80n/build-tomo-job:dev
        imagePullPolicy: Always
        name: tomo-job
        command: ['tail', '-f', '/dev/null']
        env:
        - name: CARGO_HOME
          value: /src/.cargo
        - name: USER
          value: img
        - name: REPOSITORY_URL
          value: https://github.com/p80n/build-tomo-js.git
        - name: COMMIT_HASH
          value: 8b7c2a7cf32bbf2d6a62ec7a65393fe5eb05fd4b
        securityContext:
          privileged: true
        volumeMounts:
        - name: src
          mountPath: /src
          subPath: "src/build-tomo-job"
      terminationGracePeriodSeconds: 0
      volumes:
      - name: src
        nfs:
          server: p80nas
          path: /peyton
